### PR TITLE
Added 2 themes blue-gray and trie-brown

### PR DESCRIPTION
**Pull request by Nilesh-Aditya**
## Added 2 new themes 
* Theme 1 --
theme-1
---
* Theme 2 --
theme-2

### CODE REVIEW

**Review by shravan20 — APPROVED** [review]
PR LGTM

**Comment by shravan20** [comment]
Hi @Nilesh-Aditya

Thank you for your time to contribute towards our feature request. We will review your code, and accept the PR.

**Comment by shravankb** [comment]
Why have you closed the PR?

**Comment by Nilesh-Aditya** [comment]
@shravankb my bad i was doing something else entirely
> Why have you closed the PR?

**Comment by shravan20** [comment]
PR Merged will be deployed in next release released

**Pull request merged**
