### PR TITLE
Author page and feedback form. #259

### PR DESCRIPTION
**Pull request by CrypticRevenger**
First page
first page

Author page
Author-page

Feedback 
feedback

After clicking submit 
last

### Summary by CodeRabbit

**New Features:**
- Added a comprehensive author page with a navigation bar, showcase, authors section, and contact form.
- Implemented smooth scrolling, dragging, and horizontal scrolling features for an enhanced user experience.
- Integrated Locomotive Scroll library with ScrollTrigger for advanced scroll animations.
- Introduced form validation for the contact form, ensuring the 'Submit' button is only enabled when all required fields are filled.

**Style:**
- Updated the website's aesthetics with new CSS styles for various elements, including fonts, colors, backgrounds, buttons, and forms.

### CODE REVIEW

**Comment by CrypticRevenger** [comment]
@shravan20  Please check the PR.

**Review by shravan20 — CHANGES_REQUESTED** [review]
How would this be served from the server side ? Also can we move all of this to react code.

**Comment by CrypticRevenger** [comment]
@shravan20 Serving a web page from the server side typically involves setting up a web server and using a server-side scripting language to generate and serve the HTML dynamically.  For the code I have made a Readme.md file you can excess from #261.

2. Yes, we can move to react code .

**Comment by shravan20** [comment]
Please move this as part of react code also can we keep the template design similar to existing design.

Otherwise it would look very odd.

**Comment by shravan20** [comment]
Needn't create separate PRs, include it as part of same PR for these changes.

**Comment by CrypticRevenger** [comment]
@shravan20  After merging you can edit all the template as per your requirement.
2. You meant to make a react file where I upload all this code?

**Comment by shravan20** [comment]
@CrypticRevenger: Can we connect over a call and discuss the PR? Please join the discord group in the project readme

**Comment by CrypticRevenger** [comment]
@shravan20 ok sure.

**Comment by CrypticRevenger** [comment]
I am not getting the discord link can you please share the link here.

**Comment by CrypticRevenger** [comment]
@shravan20  I have joined the server.

**Comment by CrypticRevenger** [comment]
@shravan20  I have joined the server.

**Comment by shravan20** [comment]
Marking this as closed as discussed over call. Please create a new PR

**Pull request closed without merging**
