### PR TITLE
Replaced promises syntax with async/await syntax

### PR DESCRIPTION
**Pull request by krushn-a**
#262 

Enhancement:
Refactored the code base to utilize async/await syntax 

### Summary by CodeRabbit

- Refactor: Updated `ContributorsCard` and `TemplateCard` components to use modern JavaScript syntax with `async/await` for better readability and error handling.
- New Feature: Added a `fetchData` function in `ContributorsCard` to handle asynchronous data fetching from an API, improving the component's performance and reliability.
- Bug Fix: Enhanced error handling in `ContributorsCard` and `TemplateCard` components, providing better user feedback during unexpected situations.
- Refactor: Optimized `reportWebVitals` function to use `async/await` syntax for improved code clarity and performance.

### CODE REVIEW

**Comment by krushn-a** [comment]
Hii @shravan20, I am getting this message in email 
Capture

Is there anything wrong with my PR?

**Comment by shravan20** [comment]
> Hii @shravan20, I am getting this message in email Capture
> 
> Is there anything wrong with my PR?

Can be ignored, will be reviewing this today EoD

**Review by diegoborbadev — APPROVED** [review]
Good error handling!

**Review by shravan20 — COMMENTED** [review]
_Marking it as closed since this has been already resolved._

**Pull request closed without merging**
