### PR TITLE
Adding the footer with feedback. #259

### PR DESCRIPTION
**Pull request by CrypticRevenger**
### Summary by CodeRabbit

**New Feature:**
- Added a comprehensive footer section to the main page. This includes a quote, office information, useful links, a feedback form, and a copyright notice, enhancing user interaction and providing additional information.

**Style:**
- Implemented significant CSS updates to improve the visual appearance and layout of the web page. These changes include new styles for various elements and media queries for responsive design, ensuring a seamless user experience across different devices.

### CODE REVIEW

**Comment by shravan20** [comment]
https://github.com/shravan20/github-readme-quotes/blob/main/frontend/src/index.js

@CrypticRevenger : In react, please add the footer as part of the App component here. We do not change the html code.

**Comment by CrypticRevenger** [comment]
@shravan20  Please review the PR.
Thank you.

**Comment by CrypticRevenger** [comment]
@shravan20  Can we have short call on discord  ,  I'm little bit confused .

**Comment by CrypticRevenger** [comment]
@shravan20 Can we have short call on discord , I'm little bit confused .

**Comment by shravan20** [comment]
Marking this as closed for now

**Pull request closed without merging**
