### PR TITLE
new theme

### PR DESCRIPTION
**Pull request by nandiniproothi**
added a new theme: medusa

medusa

### CODE REVIEW

**Comment by shravankb** [comment]
Hi @nandiniproothi  

Thank you for your support and time. We have considered your PR for the next release. I will have the PR accepted and deployed in the next release onwards.

Kindly meanwhile if you want to add more quotes, feel free to do.

Your contribution and efforts, thank you so much.

**Review by shravankb — APPROVED** [review]
PR LGTM

**Review by shravan20 — APPROVED** [review]
PR Approved

**Comment by shravan20** [comment]
Happy Hackotober Fest

**Pull request merged**
