### PR TITLE
Add Customizable Border Color Option to Default Layout (#332)

### LINKED ISSUE #332: Add Customizable Border Color Option to Default Layout
**Feature Request: Customizable Border Color for Default Layout**

**Is your feature request related to a problem? Please describe.**  
It would be useful to have a configurable option to set the border color for the default layout, allowing for greater flexibility in design.

**Describe the solution you'd like**  
Introduce a `borderColor` parameter to specify the border color for the default layout. If `borderColor` is not provided, the border will fall back to the current default color.

Example usage:  
`&borderColor=orange`

**Mockup for Reference**  
Border Color Example

**Additional Context**  
This feature would improve customization options, especially for cases where a different visual style is desired without modifying the entire layout theme.

**Request for Assignment**  
I would like to work on this feature and submit a pull request for it. Please assign this issue to me if approved.

### PR DESCRIPTION
**Pull request by marceloams**
### Overview
This PR introduces an option to customize the border color in the default layout, enhancing the visual flexibility of the templates.

### Changes
- Implemented a new feature allowing users to customize the border color in the default layout. 
- Updated the README with instructions on how to utilize the new border color option.

Closes #332.

## Summary by CodeRabbit

- **New Features**
	- Introduced customization of quote template border color using the `?borderColor=COLOR` parameter.
	- Added a method to set border color in quote templates.
- **Documentation**
	- Updated `README.md` to include new border color customization feature with implementation examples.
- **Enhancements**
	- Updated layout styles to dynamically assign border color based on the template's settings.
	- Enhanced the Home component to allow users to select a border color for templates.

### CODE REVIEW

**Comment by marceloams** [comment]
Thanks for the feedback, @shravan20! I actually considered adding the option to the UI. However, the current implementation only works with the default layout. One potential solution would be to display the input only when the default layout is selected. Alternatively, we could keep the input on other layouts and just include a hover message on it to inform users about this limitation. Do you have a preference or any suggestions?

**Comment by shravan20** [comment]
> Thanks for the feedback, @shravan20! I actually considered adding the option to the UI. However, the current implementation only works with the default layout. One potential solution would be to display the input only when the default layout is selected. Alternatively, we could keep the input on other layouts and just include a hover message on it to inform users about this limitation. Do you have a preference or any suggestions?

This sounds good to me. We can simply add a simple warning note about the same, which should work fine.

**Comment by marceloams** [comment]
Hey @shravan20, I've added an option to set the border color in the UI. The input is always displayed, but a warning message has been added to indicate that it only works with the default layout.

**Review by shravan20 — APPROVED** [review]
PR LGTM

Thank you for your time and efforts <3 
I really appreciate it. :)

**Pull request merged**
